python train_faster_rcnn.py \
 --dataset coco \
 --train_data_root /root/userfolder/datasets \
 --train_ann_file /root/userfolder/datasets/TCT/annotations/yzh/mini-data/train.json \
 --val_data_root /root/userfolder/datasets \
 --val_ann_file /root/userfolder/datasets/TCT/annotations/yzh/mini-data/val.json  \
 --gpus "" \
 --use-fpn \
 --num-workers 4 \
 --lr 0.0001 \
 --epochs 12 \
 --lr-decay-epoch 8,11 \
 --save-prefix tct/result \
 --batch-size 1